name: "Publish"

on:
    release:
        types: [published]

jobs:
    release:
        name: "Release"
        runs-on: ubuntu-latest
        steps:
            - name: "Checkout"
              uses: actions/checkout@v4

            - name: "Setup Node.js"
              uses: actions/setup-node@v4
              with:
                  node-version: '18'
                  registry-url: 'https://npm.pkg.github.com'
                  always-auth: true

            - name: Install dependencies and build
              run: yarn install --frozen-lockfile && yarn build

            - name: "Tests before publish"
              run: yarn test

            - name: Publish package on NPM
              run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc && yarn publish
              env:
                NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}